In [1]:
import pandas as pd

In [50]:
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/iris.csv')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df['species'].replace({'setosa': 0, 'versicolor': 1, 'virginica': 2},
                       inplace = True)

C:\Users\linde\AppData\Local\Temp\ipykernel_7444\405888724.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({

In [6]:
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [9]:
# Data Load
from sklearn import datasets

iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'frame': None, 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'), 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n|details-start|\n**References**\n|details-split|\n\n- Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n  Mathematical Statistics" (John Wiley, NY, 1950).\n- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n  Structure and Classification Rule for Recognition in Partially Exposed\n  Environments".  IEEE Transactions on Pattern Analysis and Machine\n  Intelligence, Vol. PAMI-2, No. 1, 67-71.\n- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n  on Information Theory, May 1972, 431-433.\n- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n  conceptual clustering system finds 3 classes in the data.\n- Many, many more ...\n\n|details-end|\n', 'feature_names': ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'], 'filename': 'iris.csv', 'data_module': 'sklearn.datasets.data'}

In [10]:
X = iris.data
y = iris.target

In [13]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

In [18]:
from sklearn.tree import DecisionTreeClassifier as DTC
dt = DTC(random_state=1)

In [19]:
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=1)

In [24]:
y_pred = dt.predict(X_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [30]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [32]:
f1_score(y_test, y_pred)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [33]:
from sklearn.metrics import accuracy_score

y_true = [0, 2, 1, 3]
y_pred = [0, 1, 2, 3]

# 일치하는 비율
print(accuracy_score(y_true, y_pred))

# 일치하는 개수
print(accuracy_score(y_true, y_pred, normalize = False))

0.5
2.0

In [34]:
from sklearn.metrics import confusion_matrix

y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]

# 대각 원소는 실제값과 예측값이 일치하는 경우
# 행과 열은 차례대로 0, 1, 2
# 행이 y_true
# 열이 y_pred
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

In [45]:
# data frame 정의
df = pd.DataFrame([
    [42, 'male', 12,'reading','class2'],
    [35, 'U', 3,'cooking', 'class1'],
    [1000, 'female', 7,'cycling', 'class3'],
    [1000, 'U', 21,'U', 'class4']
])
df.columns=['age',
            'gender',
            'month_birth',
            'hobby','target']
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading  class2
1    35       U            3  cooking  class1
2  1000  female            7  cycling  class3
3  1000       U           21        U  class4

In [41]:
data_value = df['target'].values
data_value

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder

In [38]:
class_label = LabelEncoder()
class_label

LabelEncoder()

In [42]:
y_new = class_label.fit_transform(data_value)
y_new

array([1, 0, 2, 3])

In [44]:
df['target'] = y_new
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading       1
1    35       U            3  cooking       0
2  1000  female            7  cycling       2
3  1000       U           21        U       3

In [46]:
y_ori = class_label.inverse_transform(y_new)
y_ori

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [47]:
df['target'] = y_ori

In [48]:
print(df)

    age  gender  month_birth    hobby  target
0    42    male           12  reading  class2
1    35       U            3  cooking  class1
2  1000  female            7  cycling  class3
3  1000       U           21        U  class4

In [62]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [51]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [56]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [54]:
from sklearn.preprocessing import MinMaxScaler

In [55]:
scaler = MinMaxScaler()
scaler.fit(X)

MinMaxScaler()

In [57]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2)

In [60]:
X_te.shape

(30, 4)

In [64]:
knn = KNN(n_neighbors=5)

In [66]:
knn.fit(X_tr, y_tr)

KNeighborsClassifier()

In [71]:
y_pred = knn.predict(X_te)
len(y_pred)

30

In [70]:
len(y_te)

30

In [72]:
accuracy_score(y_te, y_pred)

1.0

In [73]:
confusion_matrix(y_te, y_pred)

array([[ 6,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 13]], dtype=int64)

In [74]:
# 데이터 불러오기
from sklearn import datasets

raw_wine = datasets.load_wine()

In [75]:
raw_wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'frame': None,
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7'),
 'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:                    70.0 162.0    99.7  14.3\nTotal Phenols:                0.98  3.88    2.29  0.63\nFlavanoids:                   0.34  5.08    2.03  1.00\nNonflavanoid Phenols:         0.13  0.66    0.36  0.12\nProanthocyanins:              0.41  3.58    1.59  0.57\nColour Intensity:              1.3  13.0     5.1   2.3\nHue:                          0.48  1.71    0.96  0.23\nOD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\nProline:                       278  1680     746   315\n============================= ==== ===== ======= =====\n\n:Missing Attribute Values: None\n:Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners:\n\nForina, M. et al, PARVUS -\nAn Extendible Package for Data Exploration, Classification and Correlation.\nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science.\n\n|details-start|\n**References**\n|details-split|\n\n(1) S. Aeberhard, D. Coomans and O. de Vel,\nComparison of Classifiers in High Dimensional Settings,\nTech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of\nMathematics and Statistics, James Cook University of North Queensland.\n(Also submitted to Technometrics).\n\nThe data was used with many others for comparing various\nclassifiers. The classes are separable, though only RDA\nhas achieved 100% correct classification.\n(RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))\n(All results using the leave-one-out technique)\n\n(2) S. Aeberhard, D. Coomans and O. de Vel,\n"THE CLASSIFICATION PERFORMANCE OF RDA"\nTech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of\nMathematics and Statistics, James Cook University of North Queensland.\n(Also submitted to Journal of Chemometrics).\n\n|details-end|\n',
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline']}

In [76]:
# feature, target
X = raw_wine.data
y = raw_wine.target

print(X.shape)
print(y.shape)

(178, 13)
(178,)

In [77]:
# 트레이닝 / 테스트 데이터 분할
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(133, 13)
(133,)
(45, 13)
(45,)

In [78]:
# 데이터 scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaling = scaler.transform(X_train)
X_test_scaling = scaler.transform(X_test)

In [79]:
from sklearn import svm

In [80]:
svm_model = svm.SVC(kernel='linear', random_state=0)

In [81]:
svm_model.fit(X_train_scaling, y_train)

SVC(kernel='linear', random_state=0)

In [85]:
y_pred =svm_model.predict(X_test_scaling)
y_pred

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 2, 2,
       1, 2, 1, 2, 0, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 2,
       0])

In [86]:
# 평가
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

# confusion matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9555555555555556
[[13  0  0]
 [ 0 19  1]
 [ 1  0 11]]

In [87]:
# 분류 리포트
from sklearn.metrics import classification_report

class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.95      0.97        20
           2       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45

In [89]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],
    'Size': ['S', 'M', 'L', 'M', 'L'],
    'Price': [10, 20, 15, 10, 20]
})
print(df)

   Color Size  Price
0    Red    S     10
1   Blue    M     20
2  Green    L     15
3    Red    M     10
4   Blue    L     20

In [90]:
# y 정의
# dataframe 형태
y = df[['Size']]
type(y)

pandas.core.frame.DataFrame

In [92]:
print(y)

  Size
0    S
1    M
2    L
3    M
4    L

In [93]:
from sklearn.preprocessing import OneHotEncoder

In [94]:
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(y)

OneHotEncoder()

In [98]:
y_hot = onehot_encoder.transform(y)
y_hot

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [99]:
y_hot.toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [100]:
import numpy as np
X = np.array([['Korea', 44, 7200], 
['Japan', 27, 4800], 
['China', 30, 6100]])

In [107]:
XX = onehot_encoder.fit_transform(X[:,0].reshape(-1,1)).toarray()

In [ ]:
X[:,0].reshape(-1,1).

array([['Korea'],
       ['Japan'],
       ['China']], dtype='<U11')

In [108]:
X = np.delete(X, [0], axis=1)
X = np.concatenate((XX, X), axis =1)

In [120]:
onehot_color = pd.get_dummies(df['Color'], dtype=int)
print(onehot_color)

   Blue  Green  Red
0     0      0    1
1     1      0    0
2     0      1    0
3     0      0    1
4     1      0    0

    Blue  Green    Red
0  False  False   True
1   True  False  False
2  False   True  False
3  False  False   True
4   True  False  False

In [114]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],
    'Size': ['S', 'M', 'L', 'M', 'L'],
    'Price': [10, 20, 15, 10, 20]
})
print(df)

   Color Size  Price
0    Red    S     10
1   Blue    M     20
2  Green    L     15
3    Red    M     10
4   Blue    L     20

In [118]:
df_new = pd.concat([df, onehot_color], axis=1)
print(df_new)

   Color Size  Price   Blue  Green    Red
0    Red    S     10  False  False   True
1   Blue    M     20   True  False  False
2  Green    L     15  False   True  False
3    Red    M     10  False  False   True
4   Blue    L     20   True  False  False

In [121]:
onehot_color2 = pd.get_dummies(df['Color'], drop_first=True, dtype=int)
print(onehot_color2)

df_new2 = pd.concat([df, onehot_color2], axis=1)
print(df_new2)

   Green  Red
0      0    1
1      0    0
2      1    0
3      0    1
4      0    0
   Color Size  Price  Green  Red
0    Red    S     10      0    1
1   Blue    M     20      0    0
2  Green    L     15      1    0
3    Red    M     10      0    1
4   Blue    L     20      0    0

In [122]:
y

  Size
0    S
1    M
2    L
3    M
4    L

In [124]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
print(y_encoded)

[2 1 0 1 0]

c:\Programming\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [125]:
from tensorflow.keras.utils import to_categorical

In [126]:
y_hot2 = to_categorical(y_encoded)
y_hot2

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [127]:
class_vector =[2, 6, 6, 1]

output = to_categorical(class_vector, num_classes = 7)
print(output)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]]

In [27]:
Y, M, D = 1900, 2, 29

season_spring = [3, 4, 5]
season_summer = [6, 7, 8]
season_fall = [9, 10, 11]
season_winter = [12, 1, 2]

day_30 = [4, 6, 9, 11]

# 윤년 체크
def yun(Y):
    if Y % 4 == 0:
        print('Y % 4 == 0')
        return True
    elif (Y % 4 == 0) and (Y % 100 == 0):
        print('(Y % 4 == 0) and (Y % 100 == 0)')
        return False
    elif (Y % 4 == 0) and (Y % 100 == 0) and (Y % 400 == 0):
        print('(Y % 4 == 0) and (Y % 100 == 0) and (Y % 400 == 0)')
        return True
    else:
        print('yun else')
        return False

def date_check(Y, M, D):
    # 2월일 때 먼저 체크
    if M == 2:
        if D >= 30:     # 2월 날짜가 30일 이상일 때 무조건 오류
            print('2월 날짜가 30일 이상일 때 무조건 오류')
            return False
        elif (yun(Y) != 1) and (D >=29): # 윤년이 아닌데 2월 날짜가 29일 이상
            print('윤년이 아닌데 2월 날짜가 29일 이상')
            return False
        else:
            return True

    elif M in day_30:
        if D == 31:
            return False
        else:
            return True
    else:
        return True

def season_check(M):
    if M in season_spring:
        return 'Spring'
    elif M in season_summer:
        return 'Summer'
    elif M in season_fall:
        return 'Fall'
    elif M in season_winter:
        return 'Winter'
    
if date_check(Y, M, D):
    res = season_check(M)
    print(res)
else:
    print(-1)

Y % 4 == 0
Winter

In [36]:
# 윤년 체크
def yun(Y):
    if Y % 4 == 0:
        print('Y % 4 == 0')
        if Y % 100 == 0:
            print('(Y % 4 == 0) and (Y % 100 == 0)')
            if Y % 400 == 0:
                print('(Y % 4 == 0) and (Y % 100 == 0) and (Y % 400 == 0)')
                return True
            return False
        return True # 윤년이다.
    else:
        print('yun else')
        return False

def date_check(Y, M, D):
    # 2월일 때 먼저 체크
    if M == 2:
        if D >= 30:     # 2월 날짜가 30일 이상일 때 무조건 오류
            print('2월 날짜가 30일 이상일 때 무조건 오류')
            return False
        elif (yun(Y) != 1) and (D >=29): # 윤년이 아닌데 2월 날짜가 29일 이상
            print('윤년이 아닌데 2월 날짜가 29일 이상')
            return False
        else:
            return True

    elif M in day_30:
        if D == 31:
            return False
        else:
            return True
    else:
        return True

def season_check(M):
    if M in season_spring:
        return 'Spring'
    elif M in season_summer:
        return 'Summer'
    elif M in season_fall:
        return 'Fall'
    elif M in season_winter:
        return 'Winter'

In [37]:
if date_check(Y, M, D):
    res = season_check(M)
    print(res)
else:
    print(-1)

Y % 4 == 0
(Y % 4 == 0) and (Y % 100 == 0)
윤년이 아닌데 2월 날짜가 29일 이상
-1

In [38]:
A = 'aoa'
def func(str):
    new_str = str[::-1]

    return new_str

new_str = func(A)

if A == new_str:
    print('Yes')
else:
    print('No')

Yes

In [39]:
a = 'codetree'
a[::-1]

'eertedoc'

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/iris.csv')

In [5]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()

In [19]:
df[['sepal_length']] = scaler.fit_transform(df[['sepal_length']])
df[['sepal_width']] = scaler.fit_transform(df[['sepal_width']])
df[['petal_length']] = scaler.fit_transform(df[['petal_length']])
df[['petal_width']] = scaler.fit_transform(df[['petal_width']])

In [22]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [23]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=1)

In [24]:
print(X_tr.shape)

(120, 4)

In [26]:
lr = LR()
lr.fit(X_tr, y_tr)

LogisticRegression()

In [27]:
y_pred = lr.predict(X_te)

In [28]:
y_pred

array(['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica'],
      dtype=object)

In [29]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [34]:
print(classification_report(y_te, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.77      0.87        13
   virginica       0.67      1.00      0.80         6

    accuracy                           0.90        30
   macro avg       0.89      0.92      0.89        30
weighted avg       0.93      0.90      0.90        30

In [37]:
print(lr.predict_proba(X_te))

[[0.90812498 0.08399114 0.00788388]
 [0.29843322 0.5751446  0.12642218]
 [0.08478629 0.48707097 0.42814274]
 [0.89353205 0.09555247 0.01091547]
 [0.00604052 0.11619087 0.87776861]
 [0.0767756  0.3739392  0.54928519]
 [0.01022245 0.18582555 0.803952  ]
 [0.86449777 0.12044046 0.01506178]
 [0.85110676 0.14091762 0.00797563]
 [0.00694564 0.1511374  0.84191696]
 [0.13636683 0.56865758 0.29497559]
 [0.87185392 0.11340995 0.01473613]
 [0.00698578 0.19483018 0.79818404]
 [0.08924236 0.42484748 0.48591016]
 [0.08668988 0.47990516 0.43340496]
 [0.88498948 0.10961537 0.00539515]
 [0.14230569 0.60840903 0.24928528]
 [0.11398523 0.4650964  0.42091837]
 [0.81472841 0.16990438 0.01536721]
 [0.85818481 0.1348117  0.00700349]
 [0.13301978 0.59941013 0.26757009]
 [0.12547516 0.46532679 0.40919805]
 [0.03475049 0.36431434 0.60093517]
 [0.87932453 0.11237793 0.00829754]
 [0.0125519  0.23673897 0.75070913]
 [0.14867052 0.55251067 0.29881881]
 [0.92767027 0.06527837 0.00705136]
 [0.89681276 0.0941901  0.00899715]
 [0.1012545  0.56040556 0.33833994]
 [0.02123084 0.38661197 0.59215719]]

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
# 데이터 불러오기
from sklearn import datasets

raw_wine = datasets.load_wine()

In [40]:
# feature / target
X = raw_wine.data
y = raw_wine.target

print(X.shape)
print(y.shape)

print(X)
print(y)

(178, 13)
(178,)
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

In [41]:
# data split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(133, 13)
(133,)
(45, 13)
(45,)

In [42]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaling = scaler.transform(X_train)
X_test_scaling = scaler.transform(X_test)

In [43]:
# 학습
from sklearn.ensemble import RandomForestClassifier

RF_model = RandomForestClassifier(max_depth = 2, random_state = 0)

RF_model.fit(X_train_scaling, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [44]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaling = scaler.transform(X_train)
X_test_scaling = scaler.transform(X_test)

In [45]:
# 학습
from sklearn.ensemble import RandomForestClassifier

RF_model = RandomForestClassifier(max_depth = 2, random_state = 0)

RF_model.fit(X_train_scaling, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [46]:
# 예측
y_pred = RF_model.predict(X_test_scaling)
print(y_pred)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 0 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]

In [47]:
# 모형 평가
# 정확도
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

# confusion matrix
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

0.9555555555555556
[[16  0  0]
 [ 1 19  1]
 [ 0  0  8]]

In [48]:
# 분류 리포트
from sklearn.metrics import classification_report

class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       1.00      0.90      0.95        21
           2       0.89      1.00      0.94         8

    accuracy                           0.96        45
   macro avg       0.94      0.97      0.95        45
weighted avg       0.96      0.96      0.96        45

In [49]:
from sklearn.cluster import KMeans

In [50]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0        0.222222     0.625000      0.067797     0.041667     setosa
1        0.166667     0.416667      0.067797     0.041667     setosa
2        0.111111     0.500000      0.050847     0.041667     setosa
3        0.083333     0.458333      0.084746     0.041667     setosa
4        0.194444     0.666667      0.067797     0.041667     setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  virginica
146      0.555556     0.208333      0.677966     0.750000  virginica
147      0.611111     0.416667      0.711864     0.791667  virginica
148      0.527778     0.583333      0.745763     0.916667  virginica
149      0.444444     0.416667      0.694915     0.708333  virginica

[150 rows x 5 columns]

In [51]:
cluster = KMeans(n_clusters = 3, n_init=10, max_iter = 500, random_state=42)
cluster

KMeans(max_iter=500, n_clusters=3, n_init=10, random_state=42)

In [54]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [55]:
cluster.fit(X)

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(max_iter=500, n_clusters=3, n_init=10, random_state=42)

In [56]:
cluster_center = cluster.cluster_centers_

In [59]:
cluster_center

array([[0.19611111, 0.595     , 0.07830508, 0.06083333],
       [0.44125683, 0.30737705, 0.57571548, 0.54918033],
       [0.70726496, 0.4508547 , 0.79704476, 0.82478632]])

In [61]:
y_pred = cluster.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [62]:
scope = range(1, 10)
inertias = []

for k in scope:
    model = KMeans(n_clusters=k, n_init=10, max_iter=500, random_state=42)
    model.fit(X)
    inertias.append(model.inertia_)
    print(k, inertias[k-1])

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

1 41.16611042137329

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

2 12.127790750538193

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

3 6.982216473785235

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

4 5.516933472040371

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

5 4.580948640117294

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

6 3.9764242482098404

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

7 3.4736223207332464

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

8 3.145641590596779

c:\Programming\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

9 2.814016644149029

In [67]:
from mlxtend.frequent_patterns import apriori, association_rules

ModuleNotFoundError: No module named 'mlxtend'

In [66]:
!pip install mlxtend

Collecting mlxtend
  Using cached mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Collecting scipy>=1.16.3 (from mlxtend)
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting numpy>=2.3.5 (from mlxtend)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting joblib>=1.5.2 (from mlxtend)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=3 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programming\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\programming\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2023.3)
Collecting narwhals>=2.0.1 (from scikit-learn>=1.8.0->mlxtend)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=1.8.0->mlxtend)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
INFO: pip is looking at multiple versions of contourpy to determine which version is compatible with other requirements. This could take a while.
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.8->mlxtend)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: six>=1.5 in c:\programming\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.16.0)
Using cached mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB 1.3 MB/s eta 0:00:29
   ---------------------------------------- 0.2/36.5 MB 2.4 MB/s eta 0:00:16
   ---------------------------------------- 0.4/36.5 MB 3.2 MB/s eta 0:00:12
    --------------------------------------- 0.6/36.5 MB 3.7 MB/s eta 0:00:10
    --------------------------------------- 0.9/36.5 MB 4.0 MB/s eta 0:00:09
   - -------------------------------------- 1.2/36.5 MB 4.3 MB/s eta 0:00:09
   - -------------------------------------- 1.4/36.5 MB 4.6 MB/s eta 0:00:08
   - -------------------------------------- 1.7/36.5 MB 4.8 MB/s eta 0:00:08
   -- ------------------------------------- 2.0/36.5 MB 5.0 MB/s eta 0:00:07
   -- ------------------------------------- 2.4/36.5 MB 5.2 MB/s eta 0:00:07
   -- ------------------------------------- 2.7/36.5 MB 5.4 MB/s eta 0:00:07
   --- ------------------------------------ 3.1/36.5 MB 5.6 MB/s eta 0:00:07
   --- ------------------------------------ 3.4/36.5 MB 5.7 MB/s eta 0:00:06
   ---- ----------------------------------- 3.8/36.5 MB 5.9 MB/s eta 0:00:06
   ---- ----------------------------------- 4.1/36.5 MB 6.0 MB/s eta 0:00:06
   ---- ----------------------------------- 4.5/36.5 MB 6.1 MB/s eta 0:00:06
   ----- ---------------------------------- 4.9/36.5 MB 6.3 MB/s eta 0:00:06
   ----- ---------------------------------- 5.3/36.5 MB 6.3 MB/s eta 0:00:05
   ------ --------------------------------- 5.6/36.5 MB 6.4 MB/s eta 0:00:05
   ------ --------------------------------- 6.0/36.5 MB 6.5 MB/s eta 0:00:05
   ------ --------------------------------- 6.4/36.5 MB 6.6 MB/s eta 0:00:05
   ------- -------------------------------- 6.7/36.5 MB 6.6 MB/s eta 0:00:05
   ------- -------------------------------- 7.1/36.5 MB 6.7 MB/s eta 0:00:05
   -------- ------------------------------- 7.3/36.5 MB 6.7 MB/s eta 0:00:05
   -------- ------------------------------- 7.5/36.5 MB 6.4 MB/s eta 0:00:05
   -------- ------------------------------- 7.8/36.5 MB 6.5 MB/s eta 0:00:05
   -------- ------------------------------- 8.2/36.5 MB 6.5 MB/s eta 0:00:05
   --------- ------------------------------ 8.6/36.5 MB 6.6 MB/s eta 0:00:05
   --------- ------------------------------ 8.9/36.5 MB 6.6 MB/s eta 0:00:05
   ---------- ----------------------------- 9.3/36.5 MB 6.7 MB/s eta 0:00:05
   ---------- ----------------------------- 9.7/36.5 MB 6.7 MB/s eta 0:00:04
   ---------- ----------------------------- 10.0/36.5 MB 6.8 MB/s eta 0:00:04
   ----------- ---------------------------- 10.4/36.5 MB 7.0 MB/s eta 0:00:04
   ----------- ---------------------------- 10.8/36.5 MB 7.2 MB/s eta 0:00:04
   ------------ --------------------------- 11.2/36.5 MB 7.4 MB/s eta 0:00:04
   ------------ --------------------------- 11.6/36.5 MB 7.4 MB/s eta 0:00:04
   ------------- -------------------------- 11.9/36.5 MB 7.4 MB/s eta 0:00:04
   ------------- -------------------------- 12.3/36.5 MB 7.5 MB/s eta 0:00:04
   ------------- -------------------------- 12.7/36.5 MB 7.5 MB/s eta 0:00:04
   -------------- ------------------------- 13.0/36.5 MB 7.6 MB/s eta 0:00:04
   -------------- ------------------------- 13.4/36.5 MB 7.6 MB/s eta 0:00:04
   --------------- ------------------------ 13.8/36.5 MB 7.6 MB/s eta 0:00:03
   --------------- ------------------------ 14.2/36.5 MB 7.6 MB/s eta 0:00:03
   --------------- ------------------------ 14.5/36.5 MB 7.6 MB/s eta 0:00:03
   ---------------- ----------------------- 14.9/36.5 MB 7.6 MB/s eta 0:00:03
   ---------------- ----------------------- 15.3/36.5 MB 7.6 MB/s eta 0:00:03
   ----------------- ---------------------- 15.6/36.5 MB 7.6 MB/s eta 0:00:03
   ----------------- ---------------------- 16.0/36.5 MB 7.6 MB/s eta 0:00:03
   ----------------- ---------------------- 16.4/36.5 MB 7.6 MB/s eta 0:00:03
   ------------------ --------------------- 16.8/36.5 MB 7.6 MB/s eta 0:00:03
   ------------------ --------------------- 17.1/36.5 MB 7.6 MB/s eta 0:00:03
   ------------------- -------------------- 17.5/36.5 MB 7.6 MB/s eta 0:00:03
   ------------------- -------------------- 17.9/36.5 MB 8.0 MB/s eta 0:00:03
   ------------------- -------------------- 18.2/36.5 MB 8.0 MB/s eta 0:00:03
   -------------------- ------------------- 18.6/36.5 MB 8.0 MB/s eta 0:00:03
   -------------------- ------------------- 19.0/36.5 MB 8.0 MB/s eta 0:00:03
   --------------------- ------------------ 19.4/36.5 MB 8.0 MB/s eta 0:00:03
   --------------------- ------------------ 19.7/36.5 MB 8.0 MB/s eta 0:00:03
   ---------------------- ----------------- 20.1/36.5 MB 8.0 MB/s eta 0:00:03
   ---------------------- ----------------- 20.5/36.5 MB 8.0 MB/s eta 0:00:03
   ---------------------- ----------------- 20.8/36.5 MB 8.0 MB/s eta 0:00:02
   ----------------------- ---------------- 21.2/36.5 MB 8.0 MB/s eta 0:00:02
   ----------------------- ---------------- 21.6/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------ --------------- 22.0/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------ --------------- 22.3/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------ --------------- 22.7/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------- -------------- 23.1/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------- -------------- 23.5/36.5 MB 8.0 MB/s eta 0:00:02
   -------------------------- ------------- 23.8/36.5 MB 7.9 MB/s eta 0:00:02
   -------------------------- ------------- 24.2/36.5 MB 8.0 MB/s eta 0:00:02
   -------------------------- ------------- 24.6/36.5 MB 8.0 MB/s eta 0:00:02
   --------------------------- ------------ 25.0/36.5 MB 8.0 MB/s eta 0:00:02
   --------------------------- ------------ 25.3/36.5 MB 8.0 MB/s eta 0:00:02
   ---------------------------- ----------- 25.7/36.5 MB 8.0 MB/s eta 0:00:02
   ---------------------------- ----------- 26.1/36.5 MB 8.0 MB/s eta 0:00:02
   ---------------------------- ----------- 26.5/36.5 MB 8.0 MB/s eta 0:00:02
   ----------------------------- ---------- 26.8/36.5 MB 8.0 MB/s eta 0:00:02
   ----------------------------- ---------- 27.2/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------------ --------- 27.6/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------------ --------- 27.9/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------------- -------- 28.3/36.5 MB 8.0 MB/s eta 0:00:02
   ------------------------------- -------- 28.7/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------- -------- 29.1/36.5 MB 8.0 MB/s eta 0:00:01
   -------------------------------- ------- 29.5/36.5 MB 8.0 MB/s eta 0:00:01
   -------------------------------- ------- 29.8/36.5 MB 8.0 MB/s eta 0:00:01
   --------------------------------- ------ 30.2/36.5 MB 8.0 MB/s eta 0:00:01
   --------------------------------- ------ 30.6/36.5 MB 8.0 MB/s eta 0:00:01
   --------------------------------- ------ 31.0/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------- ----- 31.3/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------- ----- 31.7/36.5 MB 8.0 MB/s eta 0:00:01
   ----------------------------------- ---- 32.1/36.5 MB 8.0 MB/s eta 0:00:01
   ----------------------------------- ---- 32.4/36.5 MB 8.0 MB/s eta 0:00:01
   ----------------------------------- ---- 32.8/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------------ --- 33.2/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------------ --- 33.5/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------------- -- 33.9/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.5 MB 8.0 MB/s eta 0:00:01
   ------------------------------------- -- 34.7/36.5 MB 8.0 MB/s eta 0:00:01
   -------------------------------------- - 35.0/36.5 MB 8.0 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  35.8/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  36.5/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  36.5/36.5 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 7.5 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
   ---------------------------------------- 0.0/226.6 kB ? eta -:--:--
   ---------------------------------------  225.3/226.6 kB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 226.6/226.6 kB 4.6 MB/s eta 0:00:00
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
   ---------------------------------------- 0.0/454.8 kB ? eta -:--:--
   --------------------------- ------------ 317.4/454.8 kB 9.9 MB/s eta 0:00:01
   ---------------------------------------- 454.8/454.8 kB 7.2 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, narwhals, joblib, scipy, pandas, contourpy, scikit-learn, matplotlib, mlxtend
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 2.2.0
    Uninstalling threadpoolctl-2.2.0:
      Successfully uninstalled threadpoolctl-2.2.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Rolling back uninstall of numpy
  Moving to c:\programming\anaconda3\lib\site-packages\numpy-1.26.4.dist-info\
   from C:\Programming\anaconda3\Lib\site-packages\~-mpy-1.26.4.dist-info
  Moving to c:\programming\anaconda3\lib\site-packages\numpy\
   from C:\Programming\anaconda3\Lib\site-packages\~umpy
  Moving to c:\programming\anaconda3\scripts\f2py-script.py
   from C:\Users\linde\AppData\Local\Temp\pip-uninstall-7fbor_n2\f2py-script.py
  Moving to c:\programming\anaconda3\scripts\f2py.exe
   from C:\Users\linde\AppData\Local\Temp\pip-uninstall-7fbor_n2\f2py.exe

  ERROR: Failed to restore c:\programming\anaconda3\lib\site-packages\numpy\
  ERROR: Failed to restore c:\programming\anaconda3\scripts\f2py-script.py
  ERROR: Failed to restore c:\programming\anaconda3\scripts\f2py.exe
ERROR: Could not install packages due to an OSError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다: 'C:\\Programming\\anaconda3\\Lib\\site-packages\\numpy\\matlib.pyi'
Consider using the `--user` option or check the permissions.