# 기출 9회

In [1]:
import pandas as pd
import numpy as np

# 제1유형

In [ ]:
# 1. 데이터에서 (연도, 성별, 지역코드)별 총 대출액의 합계를 구하시오. 
# 이후, 각 (연도, 지역코드)별로 남성과 여성의 총 대출액 차이의 절댓값을 계산하고, 성별 간 총 대출액 차이가 가장 큰 지역코드를 구하시오. (총 대출액 = 금액1 + 금액2)

In [8]:
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_1.csv')
df

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

In [9]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    100 non-null    int64
 1   gender  100 non-null    int64
 2   지역코드    100 non-null    int64
 3   금액1     100 non-null    int64
 4   금액2     100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB

              year      gender        지역코드           금액1          금액2
count   100.000000  100.000000  100.000000    100.000000    100.00000
mean   2017.690000    0.390000  151.500000  50273.830000  24487.33000
std       1.624901    0.490207   30.273668  24629.946273  12344.73324
min    2015.000000    0.000000  100.000000  10301.000000   5784.00000
25%    2016.000000    0.000000  126.000000  29481.250000  13310.25000
50%    2018.000000    0.000000  155.000000  52829.000000  23073.50000
75%    2019.000000    1.000000  176.500000  69458.250000  34429.25000
max    2020.000000    1.000000  197.000000  96831.000000  47675.00000

In [10]:
df['대출액'] = df['금액1'] + df['금액2']
df

    year  gender  지역코드    금액1    금액2     대출액
0   2018       0   143  70713  43210  113923
1   2019       0   183  40306  39663   79969
2   2017       0   129  26646  41631   68277
3   2019       0   161  56843  12455   69298
4   2019       0   174  26371   9014   35385
..   ...     ...   ...    ...    ...     ...
95  2018       0   188  36641  13130   49771
96  2018       1   149  44584  24531   69115
97  2019       1   122  42745   6679   49424
98  2015       1   130  33093   8506   41599
99  2019       1   193  76105  18284   94389

[100 rows x 6 columns]

In [22]:
dfgender = df.groupby(['year','gender','지역코드'])['대출액'].sum().reset_index()
dfgender

    year  gender  지역코드     대출액
0   2015       0   131   37881
1   2015       0   151   32197
2   2015       0   195  161121
3   2015       0   197   93317
4   2015       1   101   87088
..   ...     ...   ...     ...
89  2020       1   102  105908
90  2020       1   168   85313
91  2020       1   172   97854
92  2020       1   192  109436
93  2020       1   195   34792

[94 rows x 4 columns]

In [40]:
df_pivot = dfgender.pivot_table(index=['year', '지역코드'], columns='gender', values='대출액', fill_value=0)
df_pivot['abs_diff'] = abs(df_pivot[0] - df_pivot[1])
max_code = df_pivot['abs_diff'].idxmax()
print(max_code[1])

143

In [41]:
df

    year  gender  지역코드    금액1    금액2     대출액
0   2018       0   143  70713  43210  113923
1   2019       0   183  40306  39663   79969
2   2017       0   129  26646  41631   68277
3   2019       0   161  56843  12455   69298
4   2019       0   174  26371   9014   35385
..   ...     ...   ...    ...    ...     ...
95  2018       0   188  36641  13130   49771
96  2018       1   149  44584  24531   69115
97  2019       1   122  42745   6679   49424
98  2015       1   130  33093   8506   41599
99  2019       1   193  76105  18284   94389

[100 rows x 6 columns]

In [3]:
pd.reset_option('display.max_rows')

In [5]:
# 2. 각 연도별 최대 검거율을 가진 범죄유형을 찾아서 해당 연도 및 유형의 검거건수들의 총합을 구하시오. (검거율 = 검거건수 / 발생건수)
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_2.csv')
df.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408
2,2001,발생건수,969,543,691,613,585,391,476,360,659,513
3,2001,검거건수,121,352,691,613,574,158,476,360,575,513
4,2002,발생건수,982,389,886,762,766,443,704,330,684,846

In [16]:
df1 = df[df['구분'] == '발생건수'].set_index('연도').drop(columns='구분')
df2 = df[df['구분'] == '검거건수'].set_index('연도').drop(columns='구분')
dfratio = df2 / df1
dfratio.head()

,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
연도,,,,,,,,,,
2000,1.000000,0.677165,1.000000,0.611111,1.000000,0.221111,1.000000,0.282555,1.000000,0.612613
2001,0.124871,0.648250,1.000000,1.000000,0.981197,0.404092,1.000000,1.000000,0.872534,1.000000
2002,0.122200,0.683805,0.420993,0.639108,0.913838,0.936795,0.160511,1.000000,1.000000,0.526005
2003,0.235602,1.000000,1.000000,0.178445,0.747706,1.000000,0.289548,0.893333,1.000000,1.000000
2004,0.584027,0.862217,0.523179,1.000000,1.000000,1.000000,0.929787,0.232061,1.000000,0.341253

In [17]:
max_per_year = dfratio.max(axis=1)
max_per_year

연도
2000    1.0
2001    1.0
2002    1.0
2003    1.0
2004    1.0
2005    1.0
2006    1.0
2007    1.0
2008    1.0
2009    1.0
2010    1.0
2011    1.0
2012    1.0
2013    1.0
2014    1.0
2015    1.0
2016    1.0
2017    1.0
2018    1.0
2019    1.0
2020    1.0
2021    1.0
2022    1.0
2023    1.0
2024    1.0
dtype: float64

In [18]:
def is_max_col(col):
    return col == max_per_year

mask = dfratio.apply(is_max_col, axis = 0)
mask

      범죄유형1  범죄유형2  범죄유형3  범죄유형4  범죄유형5  범죄유형6  범죄유형7  범죄유형8  범죄유형9  범죄유형10
연도
2000   True  False   True  False   True  False   True  False   True   False
2001  False  False   True   True  False  False   True   True  False    True
2002  False  False  False  False  False  False  False   True   True   False
2003  False   True   True  False  False   True  False  False   True    True
2004  False  False  False   True   True   True  False  False   True   False
2005  False   True  False  False  False   True   True   True   True   False
2006  False  False  False  False   True   True  False   True   True   False
2007  False  False  False  False  False   True   True  False  False   False
2008  False   True  False   True  False  False  False  False   True   False
2009  False  False  False   True  False  False  False  False  False   False
2010  False  False   True   True  False   True   True  False  False   False
2011   True  False   True  False  False   True  False   True   True   False
2012  False  False  False  False  False  False  False  False  False    True
2013   True   True  False   True  False   True   True  False  False    True
2014   True  False   True  False  False  False  False  False  False   False
2015  False  False  False  False   True   True   True  False   True    True
2016  False   True   True  False  False  False   True   True  False   False
2017   True  False  False   True  False  False   True  False  False   False
2018  False  False  False  False  False  False  False  False  False    True
2019   True  False   True  False  False  False  False  False  False    True
2020  False  False  False   True  False  False  False  False  False   False
2021  False  False  False   True  False  False  False  False   True    True
2022   True  False  False   True  False   True   True  False  False    True
2023  False   True   True   True  False  False   True  False  False   False
2024  False  False   True  False   True   True  False   True  False   False

In [22]:
df2_1 = df2[mask].fillna(0)
df2_1.sum().sum()

36977.0

In [24]:
# 3. 제시된 문제를 순서대로 풀고, 해답을 제시하시오.

In [25]:
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_3.csv')
df

           부서 등급     평균만족도  근속연수  교육참가횟수
0     Finance  C  4.023911  17.0     8.0
1   Marketing  A  3.756698  14.0    16.0
2          IT  B  2.628697  21.0    13.0
3   Marketing  A  3.196616   NaN    18.0
4   Marketing  C  4.770665  28.0    10.0
..        ... ..       ...   ...     ...
95         IT  A  4.884821  13.0     3.0
96  Marketing  A  4.787161  20.0    16.0
97      Sales  A  3.425397  15.0     4.0
98      Sales  A       NaN   3.0    18.0
99         HR  C  4.820796   NaN    17.0

[100 rows x 5 columns]

In [31]:
# 3.1 평균만족도: 결측치는 평균만족도 컬럼의 전체 평균으로 채우시오.
mean_t = df.groupby(['부서','등급'])['근속연수'].mean().apply(np.floor).reset_index().rename(columns={'근속연수':'평균근속연수'})
df.merge(mean_t, on=['부서','등급'],how='left')

           부서 등급     평균만족도  근속연수  교육참가횟수  평균근속연수
0     Finance  C  4.023911  17.0     8.0    11.0
1   Marketing  A  3.756698  14.0    16.0    19.0
2          IT  B  2.628697  21.0    13.0    14.0
3   Marketing  A  3.196616   NaN    18.0    19.0
4   Marketing  C  4.770665  28.0    10.0    21.0
..        ... ..       ...   ...     ...     ...
95         IT  A  4.884821  13.0     3.0    16.0
96  Marketing  A  4.787161  20.0    16.0    19.0
97      Sales  A  3.425397  15.0     4.0    17.0
98      Sales  A       NaN   3.0    18.0    17.0
99         HR  C  4.820796   NaN    17.0    12.0

[100 rows x 6 columns]

In [33]:
df['근속연수'].isnull()

0     False
1     False
2     False
3      True
4     False
      ...
95    False
96    False
97    False
98    False
99     True
Name: 근속연수, Length: 100, dtype: bool

In [53]:
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/8_3_2_train.csv')
df

    productivity      hours  age  experience
0     201.358765  49.753877   34          24
1     172.434251  35.934269   52           8
2     207.275322  51.204466   56          28
3     204.021031  40.644915   45          31
4     158.900465  37.809628   52           7
..           ...        ...  ...         ...
75    155.280256  40.052500   25           7
76    198.142554  42.313911   58          24
77    188.760119  40.887131   28          26
78    184.201724  43.887452   46          17
79    162.833865  37.451739   35           2

[80 rows x 4 columns]

In [59]:
train_X = df.drop(columns='productivity')
train_X
train_y = df['productivity']
train_y

0     201.358765
1     172.434251
2     207.275322
3     204.021031
4     158.900465
         ...
75    155.280256
76    198.142554
77    188.760119
78    184.201724
79    162.833865
Name: productivity, Length: 80, dtype: float64

In [66]:
import statsmodels.api as sm
train_X=sm.add_constant(train_X)

In [67]:
model = sm.OLS(train_y, train_X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           productivity   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     69.03
Date:                Sat, 20 Jun 2026   Prob (F-statistic):           1.20e-21
Time:                        00:33:22   Log-Likelihood:                -297.10
No. Observations:                  80   AIC:                             602.2
Df Residuals:                      76   BIC:                             611.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         67.2310     11.097      6.059      0.000      45.130      89.332
hours          1.6182      0.226      7.169      0.000       1.169       2.068
age            0.4311      0.110      3.904      0.000       0.211       0.651
experience     1.5323      0.124     12.380      0.000       1.286       1.779
==============================================================================
Omnibus:                        3.122   Durbin-Watson:                   1.692
Prob(Omnibus):                  0.210   Jarque-Bera (JB):                2.381
Skew:                           0.380   Prob(JB):                        0.304
Kurtosis:                       3.372   Cond. No.                         611.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [63]:
import statsmodels.formula.api as smf

model = smf.ols('productivity ~ hours + age + experience', data = df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           productivity   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     69.03
Date:                Sat, 20 Jun 2026   Prob (F-statistic):           1.20e-21
Time:                        00:32:34   Log-Likelihood:                -297.10
No. Observations:                  80   AIC:                             602.2
Df Residuals:                      76   BIC:                             611.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     67.2310     11.097      6.059      0.000      45.130      89.332
hours          1.6182      0.226      7.169      0.000       1.169       2.068
age            0.4311      0.110      3.904      0.000       0.211       0.651
experience     1.5323      0.124     12.380      0.000       1.286       1.779
==============================================================================
Omnibus:                        3.122   Durbin-Watson:                   1.692
Prob(Omnibus):                  0.210   Jarque-Bera (JB):                2.381
Skew:                           0.380   Prob(JB):                        0.304
Kurtosis:                       3.372   Cond. No.                         611.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [68]:
model.pvalues

const         4.892436e-08
hours         4.220961e-10
age           2.032564e-04
experience    6.655310e-20
dtype: float64