# 기출 10회

In [129]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 제1유형

In [3]:
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_1_1.csv')
df

     학생ID  문제ID 대주제  소주제  정답여부
0    1001     1  과학   동물     0
1    1001     2  사회   정치     1
2    1001     3  과학   지구     0
3    1001     4  과학   식물     0
4    1001     5  수학   측정     1
..    ...   ...  ..  ...   ...
995  1050    16  수학   소수     0
996  1050    17  수학   분수     1
997  1050    18  영어   문법     1
998  1050    19  수학  방정식     0
999  1050    20  과학   물리     0

[1000 rows x 5 columns]

In [9]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학생ID    1000 non-null   int64
 1   문제ID    1000 non-null   int64
 2   대주제     1000 non-null   object
 3   소주제     1000 non-null   object
 4   정답여부    1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

              학생ID         문제ID         정답여부
count  1000.000000  1000.000000  1000.000000
mean   1025.500000    10.500000     0.546000
std      14.438091     5.769167     0.498129
min    1001.000000     1.000000     0.000000
25%    1013.000000     5.750000     0.000000
50%    1025.500000    10.500000     1.000000
75%    1038.000000    15.250000     1.000000
max    1050.000000    20.000000     1.000000

In [10]:
print(df['대주제'].unique())
print(df['소주제'].unique())

['과학' '사회' '수학' '영어']
['동물' '정치' '지구' '식물' '측정' '듣기' '문화' '도형' '지리' '화학' '어휘' '독해' '쓰기' '역사'
 '경제' '소수' '분수' '문법' '방정식' '물리']

In [ ]:
# 1. 소주제별로 정답률(정답여부가 1인 응답수/해당 소주제 전체 응답 수)을 구하고, 3번째로 높은 정답률을 구하시오.
ratio = df.groupby('소주제')['정답여부'].mean()
ratio.sort_values(ascending=False).head()

# # 또는,
# unique_ratios = sorted(ratio.unique(), reverse=True)
# third = unique_ratios[2]
# third_subs = ratio[ratio == third].index.tolist()

# print(third, third_subs)

소주제
독해    0.74
듣기    0.70
문법    0.70
경제    0.68
지구    0.66
Name: 정답여부, dtype: float64

In [43]:
# 2. 제시된 문제를 순서대로 풀고, 해답을 제시하시오.
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_1_2.csv')
df

           date category   item   price
0    2023-01-03       커피     라떼   46123
1    2023-02-05       커피   카푸치노   77519
2    2023-03-20      스무디  망고스무디  132181
3    2023-04-01       주스  오렌지주스   32901
4    2023-05-02       커피   카푸치노   84496
..          ...      ...    ...     ...
245  2023-09-13       주스   사과주스   33558
246  2024-11-22       주스  오렌지주스  106728
247  2023-07-11      스무디  망고스무디   69927
248  2023-02-03       주스   사과주스   67808
249  2024-07-10      스무디  망고스무디   60600

[250 rows x 4 columns]

In [46]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      250 non-null    object
 1   category  250 non-null    object
 2   item      250 non-null    object
 3   price     250 non-null    int64
dtypes: int64(1), object(3)
memory usage: 7.9+ KB

               price
count     250.000000
mean   108313.180000
std     55827.465221
min     23350.000000
25%     67971.000000
50%     94091.000000
75%    141072.000000
max    268240.000000

In [ ]:
# 2.1 date를 연도(year), 월(month)로 분리하여, 연도-월별 price의 합계를 구하시오. 그 중 두번째로 큰 매출액(합계)을 구하시오.
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df

          date category   item   price  year  month
0   2023-01-03       커피     라떼   46123  2023      1
1   2023-02-05       커피   카푸치노   77519  2023      2
2   2023-03-20      스무디  망고스무디  132181  2023      3
3   2023-04-01       주스  오렌지주스   32901  2023      4
4   2023-05-02       커피   카푸치노   84496  2023      5
..         ...      ...    ...     ...   ...    ...
245 2023-09-13       주스   사과주스   33558  2023      9
246 2024-11-22       주스  오렌지주스  106728  2024     11
247 2023-07-11      스무디  망고스무디   69927  2023      7
248 2023-02-03       주스   사과주스   67808  2023      2
249 2024-07-10      스무디  망고스무디   60600  2024      7

[250 rows x 6 columns]

In [62]:
price = df.groupby(['year', 'month'])['price'].sum()
price.sort_values(ascending=False).iloc[1]
# 23년 10월 1777389

1777389

In [80]:
# 2.2 이전 문제에서 네 번째로 큰 price 합계에 해당하는 연도-월을 찾으시오. 해당 연도-월에서 카테고리별 price 합계를 구하시오. 그 중 가장 높은 price 합계(정수)를 제출하시오.
monthly_sales = price.sort_values(ascending=False)
year, month = monthly_sales.reset_index().iloc[3][['year', 'month']]
df_sub = df.loc[(df['year'] == year) & (df['month'] == month), :]
df_sub.groupby('category')['price'].sum().max()

1012500

In [101]:
# 3. 제시된 문제를 순서대로 풀고, 해답을 제시하시오.
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_1_3.csv')
df

                                               message label
0    You have won a free vacation to Hawaii! Reply ...  spam
1    Your account will be locked in 24 hours. Act now.  spam
2            Hey, are you coming to the meeting later?   ham
3       Don't forget to pick up milk on your way home.   ham
4    Special discount! 50% off on all shoes today o...  spam
..                                                 ...   ...
98                Share your feedback and win a prize.  spam
99               Call customer service for assistance.   ham
100              Don't miss the football game tonight.   ham
101              Enjoy 1-month free streaming service.  spam
102           Happy Friday! Any plans for the weekend?   ham

[103 rows x 2 columns]

In [102]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   message  103 non-null    object
 1   label    103 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB

                                                  message label
count                                                 103   103
unique                                                103     2
top     You have won a free vacation to Hawaii! Reply ...   ham
freq                                                    1    56

In [105]:
# 3.1 각 메시지의 단어 수를 공백(' ')을 기준으로 세는 새로운 컬럼을 만드시오.
df['word_count'] = df['message'].str.split(' ')
df['word_count'] = df['word_count'].apply(len)
print(df)

                                               message label  word_count
0    You have won a free vacation to Hawaii! Reply ...  spam          12
1    Your account will be locked in 24 hours. Act now.  spam          10
2            Hey, are you coming to the meeting later?   ham           8
3       Don't forget to pick up milk on your way home.   ham          10
4    Special discount! 50% off on all shoes today o...  spam           9
..                                                 ...   ...         ...
98                Share your feedback and win a prize.  spam           7
99               Call customer service for assistance.   ham           5
100              Don't miss the football game tonight.   ham           6
101              Enjoy 1-month free streaming service.  spam           5
102           Happy Friday! Any plans for the weekend?   ham           7

[103 rows x 3 columns]

In [106]:
# 3.2 'spam'과 'ham' 각각의 평균 단어 수를 계산하시오.
df.groupby('label')['word_count'].mean()

label
ham     6.232143
spam    6.531915
Name: word_count, dtype: float64

In [124]:
# 3.3 두 평균의 차이의 절댓값을 소수점 셋째자리까지 반올림하여 제출하시오.
a = df.groupby('label')['word_count'].mean()
res = np.abs(a[0] - a[1])
print(f'{res:.3f}')

0.300

C:\Users\linde\AppData\Local\Temp\ipykernel_34780\231313852.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  res = np.abs(a[0] - a[1])

# 제2유형

In [ ]:
# 제공된 학습용 데이터(10_2_train.csv)는 여러 상권 내 건물의 특성(상권 유형, 건물 면적, 건물 연식, 세대 수 등)과 연간 총 가스 소비량 정보를 담고 있다. 
# 학습용 데이터를 활용하여 건물의 연간 총 가스 소비량(gas_totl)을 예측하는 모델을 개발하고, 이 중 가장 우수한 모델을 평가용 데이터(10_2_test.csv)에 적용하여 예측 결과를 제출하시오.
# 평가 지표: RMSE

In [141]:
# data
train = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_2_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_2_test.csv')
train

        biz_type       area  age  num_households  gas_totl
0         public  93.291780   33              61       499
1    residential  97.509495   34             131      1156
2    residential  97.140181    5              30       392
3    residential  65.789408   12             166      1343
4          mixed  92.631000   28              14       154
..           ...        ...  ...             ...       ...
155   industrial  89.174291   23              94       851
156       public  97.130755   14             145      1335
157   industrial  76.334688   36             133      1157
158  residential  62.510623   37             121      1070
159       public  91.744768   31              26       387

[160 rows x 5 columns]

In [142]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   biz_type        160 non-null    object
 1   area            160 non-null    float64
 2   age             160 non-null    int64
 3   num_households  160 non-null    int64
 4   gas_totl        160 non-null    int64
dtypes: float64(1), int64(3), object(1)
memory usage: 6.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   biz_type        40 non-null     object
 1   area            40 non-null     float64
 2   age             40 non-null     int64
 3   num_households  40 non-null     int64
 4   gas_totl        0 non-null      float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.7+ KB
None

In [148]:
# 결측값 제거
train = train.loc[train['gas_totl'] != 0, :]
train_X = train.drop(columns='gas_totl', axis=1)
train_y = train['gas_totl']

test_X = test.drop(columns='gas_totl', axis=1)
test_y = test['gas_totl']

In [150]:
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

(140, 4) (140,) (40, 4) (40,)

In [152]:
# data split
from sklearn.model_selection import train_test_split
train_X, valid_X, train_y, valid_y = train_test_split(train_X, train_y, test_size=0.3, random_state=1)
print(train_X.shape, train_y.shape, valid_X.shape, valid_y.shape)

(98, 4) (98,) (42, 4) (42,)

In [ ]:
# 데이터 전처리 - 원핫인코딩
from sklearn.preprocessing import OneHotEncoder
cat_columns = train_X.select_dtypes('object').columns
num_columns = train_X.select_dtypes('number').columns
print(cat_columns)
print(num_columns)

Index(['biz_type'], dtype='object')
Index(['area', 'age', 'num_households'], dtype='object')

In [165]:
encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

train_X_cat_oh = encoder.fit_transform(train_X[cat_columns])
valid_X_cat_oh = encoder.transform(valid_X[cat_columns])
test_X_cat_oh = encoder.transform(test_X[cat_columns])

train_X_cat_oh

,biz_type_commercial,biz_type_industrial,biz_type_mixed,biz_type_public,biz_type_residential
119,0.0,0.0,1.0,0.0,0.0
86,1.0,0.0,0.0,0.0,0.0
15,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
56,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...
93,0.0,1.0,0.0,0.0,0.0
153,0.0,0.0,0.0,0.0,1.0
157,0.0,1.0,0.0,0.0,0.0
84,0.0,1.0,0.0,0.0,0.0
44,0.0,0.0,1.0,0.0,0.0

In [166]:
train_X_preprocessed = pd.concat(
    [train_X_cat_oh, train_X[num_columns]], axis=1
)
valid_X_preprocessed = pd.concat(
    [valid_X_cat_oh, valid_X[num_columns]], axis=1
)
test_X_preprocessed = pd.concat(
    [test_X_cat_oh, test_X[num_columns]], axis=1
)
train_X_preprocessed

,biz_type_commercial,biz_type_industrial,biz_type_mixed,biz_type_public,biz_type_residential,area,age,num_households
119,0.0,0.0,1.0,0.0,0.0,95.650860,39,195
86,1.0,0.0,0.0,0.0,0.0,120.873513,17,198
15,1.0,0.0,0.0,0.0,0.0,90.494853,1,96
2,0.0,0.0,0.0,0.0,1.0,97.140181,5,30
56,0.0,1.0,0.0,0.0,0.0,82.638315,22,111
...,...,...,...,...,...,...,...,...
93,0.0,1.0,0.0,0.0,0.0,108.925787,49,68
153,0.0,0.0,0.0,0.0,1.0,122.887431,46,94
157,0.0,1.0,0.0,0.0,0.0,76.334688,36,133
84,0.0,1.0,0.0,0.0,0.0,102.379570,9,192
44,0.0,0.0,1.0,0.0,0.0,73.159854,13,62

In [178]:
# 랜덤 포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=1)
rf.fit(train_X_preprocessed, train_y)

RandomForestRegressor(random_state=1)

In [173]:
from sklearn.metrics import root_mean_squared_error
pred = rf.predict(valid_X_preprocessed)

rmse = root_mean_squared_error(valid_y, pred)
rmse

75.47488439083246

In [177]:
# test 데이터로 최종 예측 수행
test_pred = rf.predict(test_X_preprocessed)
test_pred = pd.DataFrame(test_pred, columns=['pred'])
test_pred.head()

# 저장
test_pred.to_csv('result.csv', index=False)

# 제3유형

In [183]:
# 1. 한 기업이 인사관리 데이터를 가지고 이직 여부 예측 모델을 개발하려고 한다. 다음 문제를 풀이하시오.
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_3_1.csv')
df

     attrition  age  income  overtime
0            0   51    9270         0
1            0   23    9603         1
2            1   49    2860         2
3            0   56    7390         1
4            0   42    7226         2
..         ...  ...     ...       ...
195          0   36    9742         1
196          0   59    2863         0
197          0   52    4790         1
198          0   28    9408         0
199          0   58    2563         2

[200 rows x 4 columns]

In [ ]:
# 1.1 이직 여부를 예측하는 로지스틱 회귀모형을 적합하고, 유의한 변수(유의확률 0.05 미만)의 회귀계수를 소수점 셋째 자리까지 반올림하여 제출하시오. (단, 절편 제외)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   attrition  200 non-null    int64
 1   age        200 non-null    int64
 2   income     200 non-null    int64
 3   overtime   200 non-null    int64
dtypes: int64(4)
memory usage: 6.4 KB

        attrition         age       income    overtime
count  200.000000  200.000000   200.000000  200.000000
mean     0.050000   40.990000  6133.490000    0.900000
std      0.218492   11.936595  2419.029427    0.802008
min      0.000000   20.000000  2034.000000    0.000000
25%      0.000000   30.000000  4045.500000    0.000000
50%      0.000000   43.000000  6207.000000    1.000000
75%      0.000000   51.000000  8286.000000    2.000000
max      1.000000   59.000000  9989.000000    2.000000

In [191]:
import statsmodels.formula.api as smf
model = smf.logit('attrition~age+income+C(overtime)', data=df).fit()
pvalues = model.pvalues[1:]
params = model.params[1:]
print(pvalues)
print()
print(params)

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.048045
         Iterations: 35
C(overtime)[T.1]    0.997790
C(overtime)[T.2]    0.997772
age                 0.121215
income              0.009629
dtype: float64

C(overtime)[T.1]    19.463539
C(overtime)[T.2]    19.625699
age                 -0.111707
income              -0.004847
dtype: float64

c:\Programming\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [195]:
# 유의수준 0.05에서 income 변수의 pvalue가 0.05 이하이므로 유의.
sig_var = params[pvalues < 0.05]
res = np.round(sig_var, 3)
res

income   -0.005
dtype: float64

In [198]:
# 1.2 age가 1 증가할 때 이직(또는 잔류) 오즈비(odds ratio)를 소수점 셋째 자리까지 반올림하여 제출하시오.
age_coef = model.params['age']
odds_ratio_age = np.exp(age_coef)
odds_ratio_age_rounded = round(odds_ratio_age, 3)
print(odds_ratio_age_rounded)

0.894

In [203]:
# 1.3 age=20, income=3000, overtime=2 값을 가진 데이터의 이직확률을 모델로 예측하여 소수점 셋째 자리까지 반올림하여 제출하시오.
test_df = pd.DataFrame({'age':[20],
              'income':[3000],
              'overtime':[2]})
test_df

   age  income  overtime
0   20    3000         2

In [ ]:
# 예측 확률 산출
pred_prob = model.predict(test_df)
np.round(pred_prob, 3)

# # 직접 계산
# a = model.params['Intercept'] + model.params['age'] * 20 + model.params['income'] * 3000 +  model.params['C(overtime)[T.2]']
# np.exp(a)/(1+np.exp(a))

0    0.48
dtype: float64

In [217]:
# 2. 어느 지역의 주택들의 정보를 수집하여 주택 가격을 예측하는 모델을 개발하려고 한다.
# data
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/10_3_2.csv')
df

          price        area     height  wall
0    317.312359   89.934283  10.715575     0
1    273.821798   77.234714  11.121569     0
2    319.961122   92.953771  12.166102     0
3    364.561162  110.460597  12.107604     1
4    254.338664   75.316933   7.244661     1
..          ...         ...        ...   ...
195  263.625837   87.706348   9.061649     0
196  189.932311   62.322851   6.573731     0
197  282.514521   83.074502  12.707745     1
198  261.760333   81.164174   9.770920     1
199  263.929382   57.140594  12.475633     1

[200 rows x 4 columns]

In [218]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   price   200 non-null    float64
 1   area    200 non-null    float64
 2   height  200 non-null    float64
 3   wall    200 non-null    int64
dtypes: float64(3), int64(1)
memory usage: 6.4 KB

            price        area      height        wall
count  200.000000  200.000000  200.000000  200.000000
mean   278.679931   79.184581   10.171736    0.450000
std     54.055907   18.620078    1.974008    0.498742
min    134.423105   27.605098    3.517465    0.000000
25%    246.068400   65.897447    8.788325    0.000000
50%    276.676661   79.916162   10.157679    0.000000
75%    316.749275   90.017049   11.374462    1.000000
max    446.258120  134.403383   17.705463    1.000000

In [227]:
# 2.1 주택 가격을 예측하는 다중선형회귀모형을 적합하고, 유의한 변수(유의확률 0.05 미만)의 회귀계수 합(절편 제외)을 소수점 셋째 자리까지 반올림하여 제출하시오.
import statsmodels.formula.api as smf

# 다중회귀적합
model = smf.ols('price~area+height+wall', data=df).fit()
params = model.params[1:]
pvalues = model.pvalues[1:]

sig_var = params[pvalues < 0.05]
ceof_sum = sig_var.sum()
np.round(ceof_sum, 3)

10.289

In [228]:
sig_var

area      2.483000
height    7.806045
dtype: float64

In [ ]:
# 2.2 유의한 변수만으로 다중선형회귀모형을 다시 적합하고, 결정계수를 소수점 셋째 자리까지 반올림하여 제출하시오.
model = smf.ols('price ~ area +height', data=df).fit()
np.round(model.rsquared, 3)

# # 또는
# sig_var_names = sig_var.index.tolist()
# formula = 'price ~ ' + ' + '.join(sig_var_names)
# 이하 동일

0.859

In [216]:
# 2.3 area=100, height=10, wall=1 값을 가진 데이터의 예측 주택 가격을 모델로 예측하여 소수점 셋째 자리까지 반올림하여 제출하시오. (단, 이전 문제에서 뽑은 통계적으로 유의미한 변수만 선택할 것)

In [244]:
test_df = pd.DataFrame({
    'area' : [100],
    'height' : [10],
    'wall' : [1]
})
sig_var_names = sig_var.index.tolist()
test_X = test_df[sig_var_names]

# 예측
pred = model.predict(test_X)
np.round(pred, 3)

0    329.036
dtype: float64